-- 021_schema_chain_provenance.sql
--
-- Version-only provenance cannot detect an edited, skipped, or reordered
-- migration that retains the same highest filename. Extend the singleton
-- registry with a checksum-grade identity of every canonical migration
-- payload in filename order. The matching repository value is produced by
-- scripts/schema-provenance.mjs and is enforced by migration-chain/release
-- tests.
--
-- The explicitly marked checksum literal is normalized to 64 zeroes while
-- calculating this migration's canonical payload. That avoids an impossible
-- self-referential hash while still covering every other byte, including all
-- executable SQL after the stamp marker.
--
-- CONVENTION FROM HERE ON: every new migration ends with the marker and a
-- stamp of all four values printed by scripts/schema-provenance.mjs. The
-- checksum literal immediately follows the dedicated checksum-value marker;
-- that literal alone is normalized when hashing. SQL may follow it and is
-- still covered by the identity.
--
-- The migration-chain test derives those values independently and fails if the
-- chain head omits or misstates any of them. Never edit an already-applied
-- migration to update its old stamp; only the new chain head carries the new
-- identity.
--
-- APPLY: Supabase SQL editor, as postgres. Idempotent. Apply AFTER 020.

alter table urc_schema_version
  add column if not exists migration_count integer,
  add column if not exists chain_checksum text,
  add column if not exists checksum_algorithm text;

do $$ begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.urc_schema_version'::regclass
      and conname = 'urc_schema_version_migration_count_check'
  ) then
    alter table urc_schema_version
      add constraint urc_schema_version_migration_count_check
      check (migration_count > 0);
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.urc_schema_version'::regclass
      and conname = 'urc_schema_version_chain_checksum_check'
  ) then
    alter table urc_schema_version
      add constraint urc_schema_version_chain_checksum_check
      check (chain_checksum ~ '^[0-9a-f]{64}$');
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.urc_schema_version'::regclass
      and conname = 'urc_schema_version_checksum_algorithm_check'
  ) then
    alter table urc_schema_version
      add constraint urc_schema_version_checksum_algorithm_check
      check (checksum_algorithm = 'sha256-v2');
  end if;
end $$;

-- Return one typed object so callers cannot accidentally pair the version
-- from one row/read with the chain identity from another.
create or replace function urc_schema_provenance() returns jsonb
language sql stable
set search_path = pg_catalog, public
as $$
  select jsonb_build_object(
    'schemaVersion', version,
    'schemaMigrationCount', migration_count,
    'schemaChainChecksum', chain_checksum,
    'schemaChecksumAlgorithm', checksum_algorithm
  )
  from urc_schema_version
  where singleton;
$$;

do $$ begin
  execute 'revoke all on function urc_schema_provenance() from public';
  execute 'grant execute on function urc_schema_provenance() to anon, service_role';
  if exists (select 1 from pg_roles where rolname = 'urc_web') then
    execute 'grant execute on function urc_schema_provenance() to urc_web';
  end if;
end $$;

-- BEGIN URC PROVENANCE STAMP
-- Generated by: node scripts/schema-provenance.mjs
insert into urc_schema_version (
  singleton, version, migration_count, chain_checksum, checksum_algorithm
) values (
  true,
  '021',
  23,
  -- URC CHAIN CHECKSUM VALUE
  '4f83f9f24b7b4fe533bced46405f7956c4992c116470778825e5d5ad333d4db8',
  'sha256-v2'
)
on conflict (singleton) do update set
  version = excluded.version,
  migration_count = excluded.migration_count,
  chain_checksum = excluded.chain_checksum,
  checksum_algorithm = excluded.checksum_algorithm,
  applied_at = now();

alter table urc_schema_version
  alter column migration_count set not null,
  alter column chain_checksum set not null,
  alter column checksum_algorithm set not null;

-- ── Probe (separate statements) ─────────────────────────────────────────────
-- 1. select urc_schema_provenance();
--    Expect the same four scalar fields printed by:
--      node scripts/schema-provenance.mjs
-- 2. As the web identity (separate transaction):
--      set local role anon; select urc_schema_provenance();
--    Expect the same object; INSERT/UPDATE on the table remain denied.
