-- 025_rollup_refresh_and_service_budget.sql
--
-- Two freshness defects from the 2026-09 audit, both invisible to users.
--
-- 1. urc_filing_year_form (013) is the denominator behind every non-CIK
--    "N filings in scope" figure. Its own comment says "refresh after each
--    metadata ingest" — and nothing ever has. The rollup has been frozen at
--    the population it held when 013 was applied (2026-07-25); current-year
--    counts understate more every day, and the CIK path (which reads the
--    live table) disagrees with it. This adds the missing refresh routine,
--    in the same shape as the other maintenance functions, and the daily
--    refresh calls it after ingestion.
--
-- 2. The maintenance RPCs (rethread, auditor refresh, ANALYZE) carry a
--    function-level `set statement_timeout` that Postgres ignores: the
--    timer is armed when the calling statement starts (015 documents the
--    rule). They therefore run under the service role's budget — which
--    the live registry shows is UNSET (no role-level config), i.e. whatever
--    the connection inherits. A 500K-row rethread and a 6.5M-row ANALYZE are
--    one corpus-growth step from 57014 aborting the daily job. The budget is
--    now explicit at the role level, where it actually applies.
--
-- Idempotent; forward-only. Apply in the Supabase SQL editor as postgres,
-- then `notify pgrst, 'reload config'` is issued below so PostgREST picks
-- up the role setting.

-- ── 1. Refresh routine for the filing-scope denominator ──────────────────────
create or replace function public.urc_refresh_filing_year_form()
returns void language plpgsql security definer
set search_path = pg_catalog
as $$
begin
  refresh materialized view concurrently public.urc_filing_year_form;
end $$;

revoke all on function public.urc_refresh_filing_year_form()
  from public, anon, authenticated;
grant execute on function public.urc_refresh_filing_year_form()
  to service_role;
do $$ begin
  if exists (select 1 from pg_roles where rolname = 'urc_web') then
    execute 'revoke all on function public.urc_refresh_filing_year_form() from urc_web';
  end if;
end $$;

-- ── 2. An explicit statement budget for the service role ─────────────────────
-- 600s covers the largest maintenance call today (ANALYZE of the filings
-- table measured at ~39s; the auditor-period refresh and the full rethread
-- are the next largest). Web roles keep their 20s budget from 015.
alter role service_role set statement_timeout = '600s';

notify pgrst, 'reload config';
notify pgrst, 'reload schema';

-- BEGIN URC PROVENANCE STAMP
-- Generated by: node scripts/schema-provenance.mjs
insert into public.urc_schema_version (
  singleton, version, migration_count, chain_checksum, checksum_algorithm
) values (
  true,
  '025',
  27,
  -- URC CHAIN CHECKSUM VALUE
  '0142f295f8f1740506a21433bba6de51adacfc67654cfeee5dea32a114e8f1b4',
  'sha256-v2'
)
on conflict (singleton) do update set
  version = excluded.version,
  migration_count = excluded.migration_count,
  chain_checksum = excluded.chain_checksum,
  checksum_algorithm = excluded.checksum_algorithm,
  applied_at = now();
