/**
 * Action-level coverage traceability (remediation handoff WP8).
 *
 * Every action in UI_PAGE_CONTRACTS must map to EXECUTABLE evidence — a real
 * Playwright spec whose title the meta-test verifies exists — or carry an
 * owned manual exception with an expiry date. Exceptions are a debt register,
 * not a pass: when BURN_DOWN_DATE arrives, every remaining exception turns
 * the suite red by design. Burning them down means writing the behavior
 * archetype tests (navigation, form/Enter parity, combobox, chips, sort,
 * retry identity, export, dialogs, …), not editing the date.
 *
 * HONESTY RULE: an 'automated' entry may only reference a spec that actually
 * exercises the action's behavior. Page-level smoke (route renders an H1) and
 * the census audit (controls exist) do NOT count as action coverage.
 */

export const BURN_DOWN_DATE = '2026-09-30';

export type UiActionEvidence =
  | { kind: 'automated'; specs: readonly { file: string; title: string }[] }
  | { kind: 'manual-exception'; owner: string; reason: string; expires: string };

/**
 * Actions whose failure would silently corrupt research output or leak
 * authority — these may not carry exceptions past BURN_DOWN_DATE, and the
 * meta-test reports them separately so the burn-down starts here.
 */
export const CRITICAL_ACTION_IDS: readonly string[] = [
  'research-workbench.run-search',
  'research-workbench.open-filing',
  'research-workbench.save-alert',
  'dashboard.check-saved-alert',
  'comment-letters.run-search',
  'comment-letters.generate-summary',
  'filing-detail.open-sec-source',
  'global.authentication',
  'global.external-source-links',
];

export const UI_ACTION_COVERAGE: Record<string, UiActionEvidence> = {
  'landing.submit-search': { kind: 'automated', specs: [{ file: 'tests/e2e/neutral-visitor.spec.ts', title: 'hero search carries the visitor query into research' }] },
  'landing.open-dashboard': { kind: 'automated', specs: [{ file: 'tests/e2e/neutral-visitor.spec.ts', title: 'has a meaningful destination' }] },
  'landing.explore-capabilities': { kind: 'automated', specs: [{ file: 'tests/e2e/neutral-visitor.spec.ts', title: 'coverage control scrolls to the promised section' }] },
  'landing.open-capability': { kind: 'automated', specs: [{ file: 'tests/e2e/neutral-visitor.spec.ts', title: 'has a meaningful destination' }] },
  'landing.open-legal-help': { kind: 'automated', specs: [{ file: 'tests/e2e/neutral-visitor.spec.ts', title: 'opens the correct public page' }] },
  'dashboard.add-watch-company': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the dashboard page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'dashboard.open-company-research': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the dashboard page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'dashboard.remove-watch-company': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the dashboard page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'dashboard.open-recent-filing': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the dashboard page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'dashboard.check-saved-alert': { kind: 'automated', specs: [{ file: 'tests/e2e/critical-actions.spec.ts', title: 'research-workbench.save-alert and dashboard.check-saved-alert round-trip' }] },
  'dashboard.open-or-remove-alert': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the dashboard page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'earnings.run-search': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the earnings page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'earnings.open-result-source': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the earnings page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'earnings.open-recent-filing': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the earnings page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'earnings.retry-failure': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the earnings page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'research-workbench.run-search': { kind: 'automated', specs: [{ file: 'tests/e2e/boolean-search.spec.ts', title: 'a disjoint OR returns the union, not the intersection' }] },
  'research-workbench.manage-search-sessions': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the research-workbench page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'research-workbench.toggle-panels': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the research-workbench page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'research-workbench.choose-company-suggestion': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the research-workbench page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'research-workbench.save-alert': { kind: 'automated', specs: [{ file: 'tests/e2e/critical-actions.spec.ts', title: 'research-workbench.save-alert and dashboard.check-saved-alert round-trip' }] },
  'research-workbench.sort-and-page': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the research-workbench page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'research-workbench.select-result': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the research-workbench page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'research-workbench.open-filing': { kind: 'automated', specs: [{ file: 'tests/e2e/critical-actions.spec.ts', title: 'research-workbench.open-filing reaches the exact selected filing workspace' }] },
  'research-workbench.open-issuer-or-source': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the research-workbench page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'research-workbench.open-assistant-or-help': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the research-workbench page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'comment-letters.run-search': { kind: 'automated', specs: [{ file: 'tests/e2e/critical-actions.spec.ts', title: 'comment-letters.run-search renders matches from the letter corpus' }] },
  'comment-letters.apply-example-or-form': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the comment-letters page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'comment-letters.expand-thread': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the comment-letters page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'comment-letters.generate-summary': { kind: 'automated', specs: [{ file: 'tests/e2e/critical-actions.spec.ts', title: 'comment-letters.generate-summary POSTs only on explicit click and renders labeled output' }] },
  'comment-letters.open-issuer-or-edgar': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the comment-letters page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'comment-letters.retry-source': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the comment-letters page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'exhibits.choose-types': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the exhibits page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'exhibits.run-search': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the exhibits page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'exhibits.open-result-source': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the exhibits page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'exhibits.open-recent-filing': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the exhibits page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'exhibits.retry-failure': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the exhibits page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'no-action-letters.run-search': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the no-action-letters page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'no-action-letters.open-source': { kind: 'automated', specs: [{ file: 'tests/e2e/external-source-links.spec.ts', title: 'global.external-source-links names each scraped SEC index row by its document' }] },
  'no-action-letters.retry-source': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the no-action-letters page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'benchmarking.add-or-remove-company': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the benchmarking page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'benchmarking.switch-view': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the benchmarking page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'benchmarking.choose-years-or-section': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the benchmarking page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'benchmarking.build-peer-group': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the benchmarking page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'benchmarking.generate-summary-or-memo': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the benchmarking page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'benchmarking.export-results': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the benchmarking page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'accounting-analytics.add-company': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the accounting-analytics page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'accounting-analytics.remove-company': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the accounting-analytics page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'accounting-analytics.retry-facts': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the accounting-analytics page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'esg-research.switch-section': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the esg-research page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'esg-research.open-framework-source': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the esg-research page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'esg-research.manage-heatmap-companies': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the esg-research page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'esg-research.inspect-topic': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the esg-research page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'esg-research.filter-signals': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the esg-research page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'esg-research.summarize-or-open-filing': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the esg-research page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'board-profiles.load-target': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the board-profiles page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'board-profiles.manage-comparison': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the board-profiles page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'board-profiles.switch-view': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the board-profiles page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'board-profiles.retry-company': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the board-profiles page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'insider-trading.add-company': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the insider-trading page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'insider-trading.remove-company': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the insider-trading page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'insider-trading.open-source': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the insider-trading page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'accounting-standards.switch-section': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the accounting-standards page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'accounting-standards.run-disclosure-search': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the accounting-standards page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'accounting-standards.save-alert-or-memo': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the accounting-standards page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'accounting-standards.open-topic-source': { kind: 'automated', specs: [{ file: 'tests/e2e/external-source-links.spec.ts', title: 'global.external-source-links names FASB and framework sources by their standard' }] },
  'accounting-standards.manage-checklist': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the accounting-standards page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'accounting-standards.ask-guidance': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the accounting-standards page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'securities-regulation.choose-source': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the securities-regulation page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'securities-regulation.run-search': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the securities-regulation page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'securities-regulation.open-source': { kind: 'automated', specs: [{ file: 'tests/e2e/external-source-links.spec.ts', title: 'global.external-source-links names each scraped SEC index row by its document' }] },
  'securities-regulation.retry-source': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the securities-regulation page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'sec-enforcement.filter-releases': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the sec-enforcement page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'sec-enforcement.open-source': { kind: 'automated', specs: [{ file: 'tests/e2e/external-source-links.spec.ts', title: 'global.external-source-links names each scraped SEC index row by its document' }] },
  'sec-enforcement.retry-source': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the sec-enforcement page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'ipo-center.switch-section': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the ipo-center page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'ipo-center.open-analyzer': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the ipo-center page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'ipo-center.find-and-select-filing': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the ipo-center page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'ipo-center.run-analysis': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the ipo-center page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'ipo-center.open-sec-source': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the ipo-center page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'ipo-center.save-or-export-pipeline': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the ipo-center page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'ipo-center.analyze-pipeline-row': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the ipo-center page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'mna-research.switch-view': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the mna-research page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'mna-research.load-deals': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the mna-research page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'mna-research.extract-deal-details': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the mna-research page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'mna-research.find-clause-filing': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the mna-research page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'mna-research.extract-clause': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the mna-research page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'mna-research.open-sec-source': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the mna-research page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'exempt-offerings.run-search': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the exempt-offerings page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'exempt-offerings.open-result-source': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the exempt-offerings page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'exempt-offerings.open-recent-filing': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the exempt-offerings page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'exempt-offerings.retry-failure': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the exempt-offerings page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'adv-registrations.run-search': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the adv-registrations page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'adv-registrations.open-source': { kind: 'automated', specs: [{ file: 'tests/e2e/external-source-links.spec.ts', title: 'global.external-source-links names each IAPD record by its firm' }] },
  'adv-registrations.retry-search': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the adv-registrations page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'support-center.filter-guidance': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the support-center page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'support-center.open-summary-route': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the support-center page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'support-center.jump-to-section': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the support-center page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'support-center.open-feature-route': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the support-center page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'privacy.allow-analytics': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the privacy page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'privacy.decline-analytics': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the privacy page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'privacy.return-home': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the privacy page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'terms.review-limitations': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the terms page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'terms.return-home': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the terms page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'design-gallery.review-component-states': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the design-gallery page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'design-gallery.exercise-static-controls': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the design-gallery page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'company-dossier.navigate-breadcrumbs': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the company-dossier page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'company-dossier.switch-view': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the company-dossier page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'company-dossier.open-filing-source': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the company-dossier page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'company-dossier.open-comment-thread': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the company-dossier page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'company-dossier.retry-dataset': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the company-dossier page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'filing-detail.return-to-search': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the filing-detail page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'filing-detail.search-or-highlight': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the filing-detail page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'filing-detail.copy-link-or-citation': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the filing-detail page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'filing-detail.export-document-data': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the filing-detail page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'filing-detail.save-watchlist': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the filing-detail page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'filing-detail.open-sec-source': { kind: 'automated', specs: [{ file: 'tests/e2e/critical-actions.spec.ts', title: 'filing-detail.open-sec-source links to the authoritative SEC document' }] },
  'filing-detail.use-tools-panel': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the filing-detail page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'filing-detail.navigate-section': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the filing-detail page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'filing-detail.manage-note': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the filing-detail page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'filing-detail.open-assistant': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the filing-detail page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'global.sidebar-navigation': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the global page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'global.sidebar-collapse': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the global page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'global.mobile-navigation': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the global page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'global.breadcrumb-navigation': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the global page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'global.quick-find': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the global page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'global.theme-preference': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the global page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  // BLOCKED, not merely unwritten — the Playwright harness cannot observe this
  // action at all today, for two independent reasons:
  //   1. playwright.config.ts sets URC_E2E_BYPASS_AUTH on its webServer, and
  //      proxy.ts returns next() unconditionally under that flag, so no route
  //      is protected and no redirect-with-return-URL ever happens.
  //   2. CI holds no NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY (only the two Supabase
  //      secrets), so clerkEnabled is false and Layout renders "Authentication
  //      unavailable" instead of the Sign In / Get Started / UserButton
  //      controls this action names.
  // Writing an archetype now could only assert against a surface that does not
  // render — the HONESTY RULE above forbids that. Server-side authorization IS
  // covered by src/__tests__/apiAuth.test.ts (401/403/503 matrix, public-path
  // matrix, per-handler helper enforcement); what remains uncovered is the UI
  // control layer. UNBLOCK: give CI a Clerk test-instance key and add a
  // non-bypassed Playwright project, then write the archetype.
  'global.authentication': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'Blocked, not unwritten: the e2e webServer sets URC_E2E_BYPASS_AUTH (proxy.ts then protects nothing) and CI has no Clerk publishable key (so the Sign In / Get Started / account controls never render). Server-side authorization is covered by apiAuth.test.ts; the UI control layer needs a CI Clerk test key plus a non-bypassed Playwright project before an honest archetype can exist.' },
  'global.copilot-panel': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the global page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'global.memo-tray': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the global page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'global.results-table': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the global page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'global.results-toolbar': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the global page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'global.lookup-fields': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the global page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'global.tabs': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the global page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
  'global.external-source-links': { kind: 'automated', specs: [
    { file: 'tests/e2e/external-source-links.spec.ts', title: 'global.external-source-links names, secures, and preserves state on SEC links' },
    { file: 'tests/e2e/external-source-links.spec.ts', title: 'global.external-source-links names each IAPD record by its firm' },
    { file: 'tests/e2e/external-source-links.spec.ts', title: 'global.external-source-links names FASB and framework sources by their standard' },
  ] },
  'global.async-and-retry': { kind: 'manual-exception', owner: 'urc-engineering', expires: BURN_DOWN_DATE, reason: 'No executable archetype test yet for the global page; verified in the 2026-07-21 manual interaction sweep, queued for the WP8 archetype burn-down.' },
};
